'use strict';

const fs             = require('fs');
const { execSync }   = require('child_process');
const { isManuallyMarked } = require('./storage');

const CONTENT_RE = /(@claude[- ]generated|generated[- ]by[:\s]+claude|claude[:\s]+generated|\[claude\]|created\s+(by|with)\s+claude|written\s+(by|with)\s+claude|via\s+claude)/i;

const COMMIT_KEYWORDS = [
  '[claude]', 'generated by claude', 'claude generated',
  'via claude', 'created by claude', 'written by claude', 'with claude',
];

function isClaudeGenerated(filepath) {
  return isManuallyMarked(filepath) || checkContent(filepath) || checkGitLog(filepath);
}

function scanRepo() {
  let tracked = [];
  try {
    tracked = execSync('git ls-files', { encoding: 'utf8', stdio: ['pipe','pipe','ignore'] })
      .trim().split('\n').filter(Boolean);
  } catch { return []; }
  return tracked.filter(isClaudeGenerated);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function checkContent(filepath) {
  try {
    const head = fs.readFileSync(filepath, 'utf8')
      .split('\n').slice(0, 50).join('\n');
    return CONTENT_RE.test(head);
  } catch { return false; }
}

function checkGitLog(filepath) {
  try {
    const log = execSync(`git log --oneline -- "${filepath}"`,
      { encoding: 'utf8', stdio: ['pipe','pipe','ignore'] }).toLowerCase();
    return COMMIT_KEYWORDS.some(kw => log.includes(kw));
  } catch { return false; }
}

module.exports = { isClaudeGenerated, scanRepo };
