"""
Detect whether a file was generated by Claude using multiple strategies:
  1. Content markers  — @claude-generated comment in the file
  2. Git log          — commit message mentions claude
  3. Manual registry  — marked via `bugclock mark`
"""

import re
import subprocess
from pathlib import Path
from typing import List

from .storage import is_manually_marked

# Patterns recognised inside file content (any language)
_CONTENT_PATTERNS = [
    r"@claude[- ]generated",
    r"generated[- ]by[:\s]+claude",
    r"claude[:\s]+generated",
    r"\[claude\]",
    r"created\s+(?:by|with)\s+claude",
    r"written\s+(?:by|with)\s+claude",
    r"via\s+claude",
]
_CONTENT_RE = re.compile("|".join(_CONTENT_PATTERNS), re.IGNORECASE)

# Keywords in git commit messages that indicate claude-generated code
_COMMIT_KEYWORDS = [
    "[claude]",
    "generated by claude",
    "claude generated",
    "via claude",
    "created by claude",
    "written by claude",
    "with claude",
]


def is_claude_generated(filepath: str) -> bool:
    """Return True if the file is considered Claude-generated via any strategy."""
    return (
        is_manually_marked(filepath)
        or _check_file_content(filepath)
        or _check_git_log(filepath)
    )


def scan_repo() -> List[str]:
    """Return all tracked files in the repo that are Claude-generated."""
    try:
        tracked = subprocess.check_output(
            ["git", "ls-files"], text=True, stderr=subprocess.DEVNULL
        ).splitlines()
    except Exception:
        return []
    return [f for f in tracked if is_claude_generated(f)]


# ── Private helpers ───────────────────────────────────────────────────────────

def _check_file_content(filepath: str) -> bool:
    try:
        text = Path(filepath).read_text(encoding="utf-8", errors="ignore")
        # Only scan the first 50 lines — markers are always near the top
        head = "\n".join(text.splitlines()[:50])
        return bool(_CONTENT_RE.search(head))
    except Exception:
        return False


def _check_git_log(filepath: str) -> bool:
    try:
        log = subprocess.check_output(
            ["git", "log", "--oneline", "--", filepath],
            text=True,
            stderr=subprocess.DEVNULL,
        )
        lowered = log.lower()
        return any(kw in lowered for kw in _COMMIT_KEYWORDS)
    except Exception:
        return False
